[package]
name = "seestr-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.seestr]
path = ".."

[[bin]]
name = "fuzz"
path = "main.rs"
test = false
doc = false
bench = false
